### Get all contacts
GET http://localhost:3000/contacts

### Get a contact by ID
GET http://localhost:3000/contacts/68772bf1c6e6bfec174cfc22

### Create a new contact
POST http://localhost:3000/contacts
Content-Type: application/json

{
  "firstName": "Test",
  "lastName": "User",
  "email": "test.example@gmail.com",
  "favoriteColor": "red",
  "birthday": "1997-08-25T00:00:00.000+00:00"
}

### Update contact by ID
PUT http://localhost:3000/contacts/pasteidhere
Content-Type: application/json

{
  "email": "test.updatedexample@gmail.com",
  "favoriteColor": "pink",
}

### Delete contact by ID
DELETE http://localhost:3000/contacts/pasteidhere